-- US03/US04: local replica of PokeAPI data plus our own (proprietary) fields.
-- Owned by Flyway; Hibernate only validates it (spring.jpa.hibernate.ddl-auto=validate).

create table pokemon (
    id             bigint generated by default as identity primary key,

    -- Catalogue snapshot: copied from PokeAPI on every sync, read-only through the API
    pokeapi_id     integer       not null,
    name           varchar(100)  not null,
    height_dm      integer       not null check (height_dm >= 0),
    weight_hg      integer       not null check (weight_hg >= 0),
    sprite_url     varchar(500),
    image_url      varchar(500),
    category       varchar(100),
    types          text[]        not null default '{}',
    abilities      text[]        not null default '{}',
    synced_at      timestamptz   not null,

    -- Proprietary data: ours, never overwritten by a sync (limits mirror the domain's ProprietaryData)
    localized_name varchar(100),
    region         varchar(50),
    habitat        varchar(50),
    tags           text[]        not null default '{}',
    notes          varchar(1000),

    -- Optimistic locking (409 on a stale update) and audit
    version        bigint        not null default 0,
    created_at     timestamptz   not null,
    updated_at     timestamptz   not null,

    constraint uk_pokemon_pokeapi_id unique (pokeapi_id),
    constraint ck_pokemon_pokeapi_id_positive check (pokeapi_id > 0),
    constraint ck_pokemon_tags_max check (cardinality(tags) <= 10)
);

comment on table pokemon is 'Local replica of PokeAPI Pokemon (US03) enriched with proprietary data (US04)';
comment on column pokemon.tags is 'Internal classification tags: lowercase kebab-case, at most 10';
