-- ADR-008: users of the API (the "secondary collection for user management").
-- Usernames and emails are stored normalised (lower case) by the domain, so plain unique constraints suffice.

create table users (
    id            bigint generated by default as identity primary key,
    username      varchar(30)  not null,
    email         varchar(254) not null,
    password_hash varchar(100) not null,
    role          varchar(20)  not null,
    created_at    timestamptz  not null,

    constraint uk_users_username unique (username),
    constraint uk_users_email unique (email),
    constraint ck_users_role check (role in ('USER', 'ADMIN')),
    constraint ck_users_username_lowercase check (username = lower(username)),
    constraint ck_users_email_lowercase check (email = lower(email))
);

comment on column users.password_hash is 'BCrypt hash; the raw password is never stored';
